# Cloudflared tunnel configuration for b-kanban
#
# Usage: cloudflared tunnel --config cloudflared-config.yml run dev-api

tunnel: dev-api
credentials-file: /Users/jirkab/.cloudflared/f988e45e-778d-4186-9f37-1d03e7da798d.json

ingress:
  - hostname: kanban.burdych.net
    service: http://localhost:5173
  - hostname: kanban-api.burdych.net
    service: http://localhost:3211
  - hostname: kanban-convex.burdych.net
    service: http://localhost:3210
  - hostname: kanban-dashboard.burdych.net
    service: http://localhost:6791
  - service: http_status:404
